# Generated by Django 3.2.9 on 2021-11-18 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_portal', '0006_auto_20180406_0520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='container_dealer',
            new_name='car_dealer',
        ),
    ]
